Itop helm chart
Super-Visions/docker-itop pull request #5
Opened 2022-02-15 16:33 UTC by finaldzn

Hello,
First of all thank you for your itop docker image, we are using it and we thank you for it.

We manage all our services on a kubernetes cluster and manage the applications using helm charts.

In order for us to use your image cleanly, we created a itop helm chart.

Please let me know if you need something or have questions.

You can also upload this chart to a chart museum in order to have it easily available to users.

Thank you

2022-03-01 14:01 UTC, Hipska requested changes

2022-03-01 14:01 UTC, Hipska commented on helm-chart/.helmignore
> +.vscode/
Are these relevant for this helm-chart? I don't think so. Please remove in that case.

2022-03-01 14:01 UTC, Hipska commented on helm-chart/README.md
> +```
Please fix indentation and markup language. (also counts for other instances in this file.)
```suggestion
```yaml
volumeMounts:
   - mountPath: "/var/www/html/data"
     name: itop-data-pv
   - mountPath: "/var/www/html/env-production"
     name: itop-env-pv
   - mountPath: "/var/www/html/log"
     name: itop-log-pv
   - mountPath: "/var/www/html/conf"
     name: itop-conf-pv
```

```

2022-03-01 14:01 UTC, Hipska commented on helm-chart/README.md
> +  tag: 3.0.0
I think I would prefer to use this tag, so the helm chart or docs doesn't need to be updated every release.
```suggestion
  tag: 3.0
```

2022-03-01 14:01 UTC, Hipska commented on helm-chart/README.md
> +This is a helm chart used to easily deploy itop to a K8S cluster using [HELM](https://helm.sh/).
```suggestion
This is a helm chart used to easily deploy iTop to a K8S cluster using [HELM](https://helm.sh/).

```

2022-03-01 14:01 UTC, Hipska commented on helm-chart/README.md
> +## HELM CHART
```suggestion
## HELM Chart
```

2022-03-01 14:01 UTC, Hipska commented on helm-chart/README.md
> +In order to allow itop to access the itop, adding specific security context for the pod was needed, those can be found in the deployment.yaml file
> itop to access the itop

What do you mean with that?

2022-03-01 14:01 UTC, Hipska commented on helm-chart/README.md
> +This is not recommanded.
```suggestion
This is not recommended.
```

2022-03-01 14:01 UTC, Hipska commented on helm-chart/README.md
> +A mysql chart link in order to also have a db deployed to go with the itop instance.
```suggestion
A mysql chart link in order to also have a db deployed to go with the iTop instance.
```

2022-03-01 14:01 UTC, Hipska commented on helm-chart/templates/NOTES.txt
> +{{- end }}
Is this file needed? And if so, please add som more comment or description what is done here..

2022-03-01 14:01 UTC, Hipska commented on helm-chart/templates/deployment.yaml
> +              port: http
iTop has a `status.php` endpoint. Maybe something can be done with that?

https://github.com/Combodo/iTop/blob/develop/webservices/status.php

2022-03-01 14:01 UTC, Hipska commented on helm-chart/values.yaml
> +  tag: 3.0.0
```suggestion
  tag: 3.0
```

2022-03-29 08:01 UTC, Hipska commented on helm-chart/templates/deployment.yaml
> +              port: http
See example: https://demo.combodo.com/simple/webservices/status.php

2022-03-29 08:02 UTC, Hipska commented
Hi @finaldzn can you give some feedback on my questions/suggestions?

2022-03-30 08:11 UTC, finaldzn commented
@Hipska im taking care of it today. Sorry for the delay

2022-04-01 16:37 UTC, finaldzn commented on helm-chart/templates/NOTES.txt
> +{{- end }}
this is the notes showed after the installation of the chart, not really sure what more can we put there

2022-04-01 16:40 UTC, finaldzn commented
I updated it, not really sure what else we can do regarding the "notes.txt"

2022-04-04 08:10 UTC, Hipska commented on helm-chart/templates/NOTES.txt
> +{{- end }}
Okay, I have no experience with HELM, so I didn't know that. In this case it looks good to me.

2022-04-04 08:21 UTC, Hipska requested changes
Great improvements! There are still some open questions. Please give your feedback.

2022-04-04 08:21 UTC, Hipska commented on helm-chart/README.md
> +In order for iTop to support being upgraded and being restarted pvc are automacaly created.
Small typo:

```suggestion
### Volumes 

In order for iTop to support being upgraded and being restarted, pvc are automatically created.
```

2022-04-04 09:10 UTC, finaldzn commented on helm-chart/README.md
> +In order to allow itop to access the itop, adding specific security context for the pod was needed, those can be found in the deployment.yaml file
Yeah not very clear, What i meant was we need to allow the itop service (so the php app ) to access to the files on the system, i updated it

2022-04-04 09:11 UTC, Hipska commented on helm-chart/README.md
> +In order to allow itop to access the itop, adding specific security context for the pod was needed, those can be found in the deployment.yaml file
Okay thanks!

2022-04-04 09:14 UTC, Hipska approved these changes
Great, all seems clear now..

2022-04-04 09:36 UTC, finaldzn commented
Great, what i can suggest is to host the chart in a chart museum so it can be as easy to install it as is the docker image

2022-04-04 09:37 UTC, Hipska commented
Where do you suggest to add this?

2022-04-04 11:27 UTC, finaldzn commented
Either using something like this : https://github.com/helm/chart-releaser-action#example-workflow

Or packaging and then pushing the chart to a public repository, but im not sure if docker hub is compatible (a helm chart implements OCI so its supposed to be compatible with docker hub but nerver tried it  )

2022-04-04 13:30 UTC, merged